import {
  LayoutDashboard,
  Building2,
  CreditCard,
  Settings,
  Users,
  BarChart3,
  QrCode,
  Store,
  ShoppingBag,
  Palette,
  Package,
  Receipt,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  MousePointerClick,
  Globe,
  Bell,
  Key,
  Database,
  Server,
  Zap,
  HelpCircle,
  Info,
  Archive,
  History,
  Plus,
  Edit,
  UserPlus,
  Shield,
  Activity,
  FileText,
  Download,
  Image,
  Type,
  Layout,
  Sparkles,
  Layers,
  FileImage,
  Wand2,
  Eye,
  Megaphone,
  Calendar,
  Briefcase,
} from "lucide-react";

// Business type pricing structure
export const businessTypePricing = {
  "Food Mall": {
    Free: 0,
    Basic: 299,
    Pro: 699,
  },
  "Retail / E-Commerce Businesses": {
    Free: 0,
    Basic: 349,
    Pro: 799,
  },
  "Creative & Design": {
    Free: 0,
    Basic: 399,
    Pro: 899,
  },
};

// Categorized navigation items with sub-items
export const navCategories = [
  {
    id: "overview",
    label: "Overview",
    items: [
      { icon: LayoutDashboard, label: "Dashboard", id: "dashboard" },
    ],
  },
  {
    id: "businesses",
    label: "Businesses",
    items: [
      { icon: Building2, label: "All Businesses", id: "restaurants" },
      { icon: Store, label: "Food Mall", id: "businesses-foodmall" },
      { icon: ShoppingBag, label: "Retail / E-Commerce", id: "businesses-retail" },
      { icon: Palette, label: "Creative & Design", id: "businesses-creative" },
      { icon: Package, label: "Pending Approval", id: "businesses-pending" },
      { icon: Archive, label: "Archived", id: "businesses-archived" },
    ],
  },
  {
    id: "users",
    label: "User Management",
    items: [
      { icon: Users, label: "All Users", id: "users" },
      { icon: UserPlus, label: "Add User", id: "users-add" },
      { icon: Shield, label: "Roles & Permissions", id: "users-roles" },
      { icon: Activity, label: "User Activity", id: "users-activity" },
    ],
  },
  {
    id: "subscriptions",
    label: "Subscriptions",
    items: [
      { icon: CreditCard, label: "All Subscriptions", id: "subscriptions" },
      { icon: TrendingUp, label: "Active Plans", id: "subscriptions-active" },
      { icon: TrendingDown, label: "Expired Plans", id: "subscriptions-expired" },
      { icon: Receipt, label: "Payment History", id: "subscriptions-payments" },
      { icon: Calendar, label: "Renewals", id: "subscriptions-renewals" },
    ],
  },
  {
    id: "plans",
    label: "Custom Plans",
    items: [
      { icon: Package, label: "All Plans", id: "plans" },
      { icon: Plus, label: "Create Plan", id: "plans-create" },
      { icon: Edit, label: "Manage Plans", id: "plans-manage" },
    ],
  },
  {
    id: "advertisements",
    label: "Advertisement Manager",
    items: [
      { icon: BarChart3, label: "Dashboard Overview", id: "ads-dashboard" },
      { icon: Plus, label: "Create Advertisement", id: "ads-create" },
      { icon: Activity, label: "Active Campaigns", id: "ads-active" },
      { icon: Calendar, label: "Scheduled Ads", id: "ads-scheduled" },
      { icon: FileText, label: "Drafts", id: "ads-drafts" },
      { icon: TrendingUp, label: "Analytics & Performance", id: "ads-analytics" },
      { icon: Settings, label: "Global Settings", id: "ads-settings" },
    ],
  },
  {
    id: "analytics",
    label: "Analytics & Reports",
    items: [
      { icon: BarChart3, label: "Overview Analytics", id: "analytics" },
      { icon: PieChart, label: "Business Analytics", id: "analytics-businesses" },
      { icon: LineChart, label: "Revenue Analytics", id: "analytics-revenue" },
      { icon: MousePointerClick, label: "QR Scan Analytics", id: "analytics-qr" },
      { icon: FileText, label: "Custom Reports", id: "reports" },
      { icon: Download, label: "Export Data", id: "reports-export" },
    ],
  },
  {
    id: "website",
    label: "Website Customization",
    items: [
      { icon: Globe, label: "General Settings", id: "website-general" },
      { icon: Image, label: "Logo & Branding", id: "website-logo" },
      { icon: Type, label: "Typography", id: "website-typography" },
      { icon: Palette, label: "Colors & Theme", id: "website-colors" },
      { icon: Layout, label: "Layout & Structure", id: "website-layout" },
      { icon: FileImage, label: "Images & Media", id: "website-media" },
      { icon: Sparkles, label: "Animations & Effects", id: "website-animations" },
      { icon: Layers, label: "Sections & Components", id: "website-sections" },
      { icon: Wand2, label: "SEO & Meta Tags", id: "website-seo" },
      { icon: Eye, label: "Preview & Publish", id: "website-preview" },
      { icon: Briefcase, label: "Our Services", id: "website-services" },
    ],
  },
  {
    id: "system",
    label: "System",
    items: [
      { icon: Settings, label: "General Settings", id: "settings" },
      { icon: Key, label: "API Keys", id: "settings-api" },
      { icon: Database, label: "Database", id: "settings-database" },
      { icon: Server, label: "Server Status", id: "settings-server" },
      { icon: Bell, label: "Notifications", id: "settings-notifications" },
      { icon: Zap, label: "Performance", id: "settings-performance" },
      { icon: History, label: "Audit Log", id: "settings-audit" },
    ],
  },
  {
    id: "support",
    label: "Support",
    items: [
      { icon: HelpCircle, label: "Help Center", id: "support-help" },
      { icon: Info, label: "System Info", id: "support-info" },
    ],
  },
  {
    id: "notifications",
    label: "Notifications",
    items: [
      { icon: Bell, label: "All Notifications", id: "notifications" },
    ],
  },
];

// Business type options for admin
export const adminBusinessTypeOptions: Record<string, string[]> = {
  "Food Mall": [
    "Restaurants",
    "Cafés",
    "Hotels",
    "Cloud Kitchens",
    "Food Courts / Fast Foods",
    "Bakeries",
    "Bars & Pubs",
    "Coffee Shops",
  ],
  "Retail / E-Commerce Businesses": [
    "Fashion & Apparel",
    "Electronics",
    "Home & Living",
    "Beauty & Personal Care",
    "Sports & Outdoors",
    "Books & Media",
    "Toys & Games",
    "Automotive",
  ],
  "Creative & Design": [
    "Graphic Design",
    "Web Design",
    "Photography",
    "Videography",
    "Branding",
    "Interior Design",
    "Architecture",
    "Digital Marketing",
  ],
};
